name: water_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # 视觉与交互基础
  cupertino_icons: ^1.0.8
  
  # 状态管理核心（必须添加）
  provider: ^6.1.1
  
  # 网络与协议层
  http: ^1.6.0
  http2: ^2.3.1
  crypto: ^3.0.7
  
  # 本地存储与工具
  shared_preferences: ^2.5.4
  intl: ^0.19.0
  
  # 硬件与多媒体
  mobile_scanner: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # 如果后续需要自定义字体或图片资源，请在此处添加 assets 声明